### ISSUE TITLE
GET https://us-east-1.pyroclast.io/js/pyroclast.js 404

### ISSUE THREAD

**Issue by robertluo** [onyx-platform/pyroclast-support#20]
Caused all my topics, services, deployments disappeared.

**Comment by lbradstreet** [comment]
I'm just encountered a similar issue after logging out and then in again. I
think there may be an issue with the login flow on the first login. Could
you try refreshing after logging in and let me know if your services show
up?

**Comment by robertluo** [comment]
It stays on "loading" infinitely, with "POST https://us-east-1.pyroclast.io/api 500" error in development console.

**Comment by lbradstreet** [comment]
@robertluo can you please try loading it again? A tagged literal made it into a pipeline and it's unable to be read back. I believe I've fixed it now.

**Comment by robertluo** [comment]
Yes. I get my things back. Thanks.

**Comment by MichaelDrogalis** [comment]
I've tracked down the root cause. Fix pending.

**Comment by MichaelDrogalis** [comment]
Partial fix made it's way to master.

**Comment by MichaelDrogalis** [comment]
Full fix going out for this today.
