### ISSUE TITLE
wrong deployment state report

### ISSUE THREAD

**Issue by robertluo** [onyx-platform/pyroclast-support#21]
my deployment https://us-east-1.pyroclast.io/svc/JX7axnw7EQ9dyv reported in console as "scheduled", but the output topic already shows 35K records and its content looks alright.

**Comment by lbradstreet** [comment]
I believe this is fixed now. Leaving this open until we've beaten on it in production.

**Comment by MichaelDrogalis** [comment]
Full fix is going out for this today in both us-east-1 & CN.
